name: 3D Contribution Graph
on:
  schedule:
    - cron: '0 0 * * *' # runs daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@main
        with:
          username: KISeam
